services:
  backend:
    build:
      context: ./services/flask_server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./services/flask_server/.env
    environment:
      DOCKER_ENV: true
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    env_file:
      - ./services/flask_server/.env
    environment:
      POSTGRES_USER: postgres
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    env_file:
      - ./services/client/.env
    depends_on:
      - backend

volumes:
  pgdata:
